version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: app
    ports:
      - ${API_PORT}:${API_PORT}
    command: bash -c "npm run test"
    restart: always
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=practice-gcb-joao-camargo-test
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_ENTITIES=src/**/*.entity.ts
      - TYPEORM_ENTITIES_DIR=src/entities
      - TYPEORM_MIGRATIONS=src/database/migrations/**/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/database/migrations
      - API_PORT=${API_PORT}
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: practice-gcb-joao-camargo-test
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_TCP_PORT: ${TYPEORM_PORT}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: