version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - $API_PORT:3000
    command: npm run start
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_TCP_PORT: ${TYPEORM_PORT}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  
